language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without development
before_install:
  -  gem update --system 2.1.11
script:
  - bundle exec rake spec
  - bundle exec rake syntax
  - bundle exec rake lint
notifications:
  email:
    - biemond@gmail.com
env:
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.1
  - PUPPET_VERSION=3.6.2